### Импорт библиотеки NumPy

In [1]:
import numpy as np

### Примеры создания массивов:

- из обычных списков

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

- с использованием функции ones

In [3]:
arr2 = np.ones(5)
arr2

array([1., 1., 1., 1., 1.])

### Демонстрация атрибутов:

In [ ]:
arr1.shape

(5,)

In [5]:
arr1.dtype

dtype('int64')

### Примеры индексирования и срезов:

- получение отдельного элемента

In [6]:
arr1[0]

np.int64(1)

- срез списка

In [7]:
arr1[1:5]

array([2, 3, 4, 5])

### Примеры векторных операций и базовых статистик:

- поэлементное сложение

In [8]:
arr1 + arr2

array([2., 3., 4., 5., 6.])

- вычисление средней величины (mean) или другой простой статистики

In [9]:
np.mean(arr1)

np.float64(3.0)